name: Release
on:
  push:
    branches:
      - main

# permissions:
# contents: read # for checkout

permissions: write-all
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
    # issues: write # to be able to comment on released issues
    # pull-requests: write # to be able to comment on released pull requests
    # id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Test push file
        run: |
          echo $(date +%s) > abc
          git add abc
          git commit -m 'add abc'
          git push -f origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      # - name: Semantic Release
      #   uses: cycjimmy/semantic-release-action@v4
      #   id: semantic
      #   with:
      #     extra_plugins: |
      #       "@semantic-release/changelog"
      #       "@semantic-release/exec"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Do something when a new release published
      #   if: steps.semantic.outputs.new_release_published == 'true'
      #   run: |
      #     echo ${{ steps.semantic.outputs.new_release_version }}
      #     echo ${{ steps.semantic.outputs.new_release_major_version }}
      #     echo ${{ steps.semantic.outputs.new_release_minor_version }}
      #     echo ${{ steps.semantic.outputs.new_release_patch_version }}
