on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: main
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
